[package]
name = "moxi-observability"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
moxi-contracts = { path = "../moxi-contracts" }
moxi-runtime = { path = "../moxi-runtime" }
moxi-store = { path = "../moxi-store" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
