[package]
name = "moxi-shells"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
chrono.workspace = true
moxi-contracts = { path = "../moxi-contracts" }
moxi-entry = { path = "../moxi-entry" }
moxi-runtime = { path = "../moxi-runtime" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
